---
version: "2.1"
services:
  endlessh:
    image: lscr.io/linuxserver/endlessh:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - MSDELAY=10000 #optional
      - MAXLINES=32 #optional
      - MAXCLIENTS=4096 #optional
      - LOGFILE=true #optional
      - BINDFAMILY= #optional
    volumes:
      - /var/log:/config/logs/ #optional
    ports:
      - 22:2222
    restart: unless-stopped
