version: "3"

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /tank/nextcloud_docker/db:/var/lib/mysql
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: "nextcloud:${TAG}"
    restart: always
    ports:
      - 8085:80
    volumes:
      - /tank/nextcloud_docker/data:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  cron:
    image: "nextcloud:${TAG}"
    restart: always
    volumes:
      - /tank/nextcloud_docker/data:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
