version: "3"
services:
  watchtower:
    image: containrrr/watchtower 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 04 04 * * *" --stop-timeout 240s --rolling-restart
    restart: unless-stopped
