version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
  # This image has been unmaintained for quite some time, this is why we build it ourself.
  # image: kylemanna/openvpn
    build:
      dockerfile: ./Dockerfile
      context: ./buildfiles
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: unless-stopped
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
